# Select image from https://hub.docker.com/_/php/
image: php:7

# Select what we should cache
cache:
  paths:
  - vendor/

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git -yqq

# Install composer
- curl -sS https://getcomposer.org/installer | php

# Install all project dependencies
- php composer.phar install
- php composer.phar update

services:
- postgres

variables:
  # Configure pgsql service (https://hub.docker.com/r/_/postgres/)
  POSTGRES_PASSWORD: mysql

# We test PHP7 (the default) with pgSQL
test:pgsql:
  script:
  - vendor/bin/phpunit --configuration phpunit_pgsql.xml --coverage-text

# We test PHP7 with pgSQL, but we allow it to fail
test:php7:pgsql:
  image: php:7.1
  script:
  - vendor/bin/phpunit --configuration phpunit_pgsql.xml --coverage-text